### PR TITLE
Revert "Fix tinder-unblur-likes.js since element class changed & add recently active text"

### PR DESCRIPTION
**Pull request by hm-harshit**
Reverts hm-harshit/Tinder-Unblur-Likes#1

### CODE REVIEW

**Comment by DarkVillager** [comment]
why?

**Comment by hm-harshit** [comment]
@DarkVillager it works like a charm when you click on the likes and then it will open all the blur profiles.  then try to run the script in console.
image

**Comment by DarkVillager** [comment]
> @DarkVillager it works like a charm when you click on the likes and then it will open all the blur profiles. then try to run the script in console. image

ah

**Comment by psoffie04** [comment]
revert-1-main

**Comment by mattgoods36** [comment]
doesn't work

**Pull request merged**
